import type { Metadata } from "next";
import { DM_Sans, Lora } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/ui/theme-provider";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { ClerkProvider } from "@clerk/nextjs";

const lora = Lora({
  subsets:['latin'],
  weight : ["400", "500"],
  style : ["normal", "italic"],
  variable: "--font-serif",
});

const dmsans = DM_Sans({
  subsets: ['latin'],
  weight : [ "300", "400", "500", "600"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons : "/favicon.png", 
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
        <ClerkProvider>
        <html
          lang="en"
          suppressHydrationWarning
        >
          <body className={`${lora.variable} ${dmsans.variable} font-sans`}>
              <ThemeProvider
              attribute="class"
              defaultTheme="dark"
              enableSystem
              disableTransitionOnChange
              >
              <main>
              <Header/>
              {children}
              <Footer/>
              </main>
            </ThemeProvider>
          </body> 
        </html>
      </ClerkProvider>
      );
    }
